# set up input/output constraints on the 100 MHz clock generated by the PLL

set_output_delay -clock {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]} -max 3 {SRAM_UB_N_O} -add_delay
set_output_delay -clock {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]} -max 3 {SRAM_LB_N_O} -add_delay

set_output_delay -clock {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]} -min 2 {SRAM_UB_N_O} -add_delay
set_output_delay -clock {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]} -min 2 {SRAM_LB_N_O} -add_delay

# Specify the false paths between 50 MHz and 100 MHz clocks

set_false_path -from clk_50 -to {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]}
set_false_path -from {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]} -to clk_50

# Specify the false paths on I/Os

set_false_path -from [all_inputs] -to {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]}
set_false_path -from {SRAM_unit|Clock_100_PLL_inst|altpll_component|auto_generated|pll1|clk[0]} -to [all_outputs]


